name: Monthly Job

on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' # Sostituisci 'x' con la versione di Python desiderata
      
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Run Script
        run: python main.py
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.json
